### ISSUE TITLE
There is no license

### ISSUE THREAD

**Issue by mrcolbyrussell** [ceritium/bookmarklet-generator#1]
There is no copy of the applicable license(s), for either the bookmarklet generator itself (convenient), or for Svelte or Vite (required—see the software license terms: [MIT License](https://opensource.org/license/mit/#:~:text=The%20above%20copyright%20notice%20and%20this%20permission%20notice%20shall%20be%20included%20in%20all%20copies%20or%20substantial%20portions%20of%20the%20Software.)).

**Comment by ceritium** [comment]
Many thanks for the reminder. Done https://github.com/ceritium/bookmarklet-generator/blob/master/LICENSE
